### PR TITLE
[Merged by Bors] - Support ClusterIP service type

### LINKED ISSUE #3: ClusterIP ListenerClass mode
We currently implemented this for a few operators in https://github.com/stackabletech/issues/issues/254, this must be supported before we can migrate those operators over.

### PR DESCRIPTION
**Pull request by dervoeti**
# Description

Fixes #3.
Depends on https://github.com/stackabletech/operator-rs/pull/602 to be merged.

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by sbernauer — COMMENTED** [review]
The actual change looks good to me and works fine.
I think we should have a short discussion regarding support for headless services (without ClusterIP) - do we want to support them, if so: how?
Sadly currently a bit limited time wise :/

**Comment by dervoeti** [comment]
Hmm yeah, not sure if we're gonna need it. I don't know the whole story here, but as far as I saw it, the main reason for the ClusterIP service was "this service should only be accessible from inside the Kubernetes cluster" (aka no LoadBalancer or NodePort), so that's solved. Also, headless services might introduce some DNS caching issues in the products (since the service resolves to a possibly changing Pod IP instead of a constant internal IP). A good reason to support them would be parity with Kubernetes features, though. And they might improve performance in some cases, but I don't know if we have explicit customer requests for this yet.

**Review by sbernauer — APPROVED** [review]
After the merge of https://github.com/stackabletech/operator-rs/pull/602 we are now forced to implement this when we upgrade operator-rs.
Thinking about it i would say this PR is fine, we can always add a new service type such as `Headless`, which is only used for dns records and not an *actual* ClusterIP.
The only drawback I see is that people might slap a ClusterIP on everything, where a headless service would be sufficient.

**Pull request closed without merging**
