### PR TITLE
fix(helm): resource names

### LINKED ISSUE #128: ServiceAccount can't be found when used as a subchart
### Affected version

23.11.0

### Current and expected behavior

I am using the listener-operator within a subchart that is named `stackable-operators`. Unfortunately I am getting the following error:
> error looking up service account stackable-system/stackable-operators-serviceaccount: serviceaccount "stackable-operators-serviceaccount" not found

I expect that using the listener-operator within a subchart is working.

### Possible solution

The listener-operator chart creates a ServiceAccount: https://github.com/stackabletech/listener-operator/blob/3ecc84029f3430e494bb0edb9c6e229df5ffa043/deploy/helm/listener-operator/templates/serviceaccount.yaml#L4-L6
The name is built like: `{{ include "operator.fullname" . }}-serviceaccount`

Having a look at the deployment this one is building the name out of a different pattern `{{ .Release.Name }}-serviceaccount`: https://github.com/stackabletech/listener-operator/blob/3ecc84029f3430e494bb0edb9c6e229df5ffa043/deploy/helm/listener-operator/templates/controller-deployment.yaml#L27

I think the `.Release.Name` should not be used here and the same approach should be used to derive the service account name.

Besides that I noticed that the deployment name is also derived from the `.Release.Name`, this should be changed as well. In other Helm charts the deployment names will not be derived from the release-name, see for example here: https://github.com/stackabletech/commons-operator/blob/main/deploy/helm/commons-operator/templates/deployment.yaml#L5

Right now my deployment is named `stackable-operators-controller-deployment` cause my main chart is named `stackable-operators` that contains the listener-operator as a subchart.

### Additional context

_No response_

### Environment

_No response_

### Would you like to work on fixing this bug?

None

### PR DESCRIPTION
**Pull request by razvan**
# Description

Fixes #128

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [x] Changes are OpenShift compatible
- [x] CRD changes approved
- [x] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/style-guide).
- [x] Helm chart can be installed and deployed operator works
- [x] Integration tests passed (for non trivial changes)
- [x] Changes need to be \"offline\" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

### CODE REVIEW

**Review by maltesander — COMMENTED** [review]
LGTM! Did you check if the secret op as well?

**Comment by razvan** [comment]
> LGTM! Did you check if the secret op as well?

Yes. Secret is fine.

**Review by maltesander — APPROVED** [review]
LGTM!

**Comment by sbernauer** [comment]
Thanks for fixing this!

**Pull request merged**
