### PR TITLE
[Merged by Bors] - Allow configuring CSI docker images

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

Fixes https://github.com/stackabletech/listener-operator/issues/60. For https://github.com/orgs/stackabletech/discussions/14
Backport of https://github.com/stackabletech/secret-operator/pull/235 for listener-operator

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by nightkr** [comment]
You also need to update the controller:

https://github.com/stackabletech/listener-operator/blob/55fd4a35b12f758f8698e64cf746241920d39a5c/deploy/helm/listener-operator/templates/controller-deployment.yaml#L47-L52

**Comment by sbernauer** [comment]
Good catch, thx! We actually do thing differently here

**Review by nightkr — APPROVED** [review]
LGTM, changelog still needs update though

**Comment by sbernauer** [comment]
bors r+
Thx for review!

**Pull request closed without merging**
