### PR TITLE
Use ClusterResources for Listener controller

### LINKED ISSUE #221: Use `ClusterResources` to manage objects created by Listener controller
From https://github.com/stackabletech/operator-rs/issues/861

### PR DESCRIPTION
**Pull request by nightkr**
# Description

Fixes #221

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [x] Changes are OpenShift compatible
- [x] Helm chart can be installed and deployed operator works
- [x] Integration tests passed (for non trivial changes)
- [x] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [x] Code contains useful comments
- [x] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [x] Changelog updated
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

### CODE REVIEW

**Review by sbernauer — CHANGES_REQUESTED** [review]
Testing this using the hdfs-op getting started guide I get the following error
`2024-10-11T06:46:22.037036Z ERROR stackable_operator::logging::controller: Failed to reconcile object controller.name="listener.listeners.stackable.tech" error=reconciler for object Listener.v1alpha1.listeners.stackable.tech/listener-simple-hdfs-namenode-default-0.default failed error.sources=[failed to apply Service.v1./listener-simple-hdfs-namenode-default-0.default, label "app.kubernetes.io/instance" contains unexpected values - expected "listener-simple-hdfs-namenode-default-0", got "simple-hdfs"]`

Can we please run the hdfs-operator kuttl suite with this listener-op version before merging?

**Comment by nightkr** [comment]
Oh, ouch. Looking into that.

**Comment by nightkr** [comment]
Looks like that's due to https://github.com/stackabletech/operator-rs/issues/887.

**Comment by nightkr** [comment]
@sbernauer Should be fixed by f462cafebf6cb03034ecb8b2a7a4b824675bdf8f.

**Comment by nightkr** [comment]
HDFS tests passed, aside from some flakiness in `smoke_hadoop-3.4.0_zookeeper-3.9.2_zookeeper-latest-3.9.2_number-of-datanodes-2_datanode-pvcs-2hdd-1ssd_listener-class-cluster-internal_openshift-false`.

**Review by sbernauer — APPROVED** [review]

**Pull request merged**
